/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihansemangat;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Hilzam
 */
public class futsal_primavera extends javax.swing.JFrame {
    int total,tunai,kembalian;
    /**
     * Creates new form futsal_primavera
     */
    public futsal_primavera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttipelapanganvoice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtjenislapvoice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtlamavoice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cksepatuvoice = new javax.swing.JCheckBox();
        ckkostumvoice = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        test = new javax.swing.JLabel();
        lblbayarkostum = new javax.swing.JLabel();
        lblbayarsepatu = new javax.swing.JLabel();
        lblbayar1 = new javax.swing.JLabel();
        lblbayarsepatu1 = new javax.swing.JLabel();
        lblbayarkostum1 = new javax.swing.JLabel();
        lblbayar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rdnindoor = new javax.swing.JRadioButton();
        rdnoutdoor = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cmbjenislap = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtlamasewa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cksepatu = new javax.swing.JCheckBox();
        ckkostum = new javax.swing.JCheckBox();
        btnhitung = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("ROG Fonts", 1, 36)); // NOI18N
        jLabel1.setText("FutsaLz");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("============Invoice Futsalz===============");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Jenis Lapangan");

        txttipelapanganvoice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txttipelapanganvoice.setEnabled(false);
        txttipelapanganvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipelapanganvoiceActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Tipe Lapangan");

        txtjenislapvoice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtjenislapvoice.setEnabled(false);
        txtjenislapvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjenislapvoiceActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("Lama Sewa");

        txtlamavoice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtlamavoice.setEnabled(false);
        txtlamavoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlamavoiceActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("Jam");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setText("Tambahan");

        cksepatuvoice.setText("Sepatu");
        cksepatuvoice.setEnabled(false);

        ckkostumvoice.setText("Kostum");
        ckkostumvoice.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setText("=========================================");

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setText("Total : ");

        txttotal.setEnabled(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setText("Tunai :");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel16.setText("Kembalian :");

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbayarKeyTyped(evt);
            }
        });

        txtkembalian.setEnabled(false);
        txtkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalianActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel17.setText("======================================");

        lblbayarkostum.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblbayarkostum.setText("-");

        lblbayarsepatu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblbayarsepatu.setText("- ");

        lblbayar1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblbayar1.setText("/ Jam");

        lblbayarsepatu1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblbayarsepatu1.setText("/ Jam");

        lblbayarkostum1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblbayarkostum1.setText("/ Jam");

        lblbayar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblbayar.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15))
                                    .addGap(69, 69, 69)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtbayar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(100, 100, 100)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel12)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckkostumvoice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblbayarkostum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblbayarkostum1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cksepatuvoice)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(test))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblbayarsepatu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblbayarsepatu1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txttipelapanganvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtlamavoice, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addComponent(txtjenislapvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblbayar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblbayar1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel9)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel10)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttipelapanganvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(test))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjenislapvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbayar1)
                            .addComponent(lblbayar))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlamavoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cksepatuvoice)
                            .addComponent(lblbayarsepatu)
                            .addComponent(lblbayarsepatu1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckkostumvoice)
                    .addComponent(lblbayarkostum)
                    .addComponent(lblbayarkostum1))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel15)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel17)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jLabel9)
                    .addContainerGap(457, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Tipe Lapangan");

        buttonGroup1.add(rdnindoor);
        rdnindoor.setText("Indoor");
        rdnindoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnindoorActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdnoutdoor);
        rdnoutdoor.setText("Outdoor");
        rdnoutdoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnoutdoorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Jenis Lapangan");

        cmbjenislap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Lapangan", "Reguler", "Matras", "Rumput" }));
        cmbjenislap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjenislapActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Lama Sewa");

        txtlamasewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlamasewaActionPerformed(evt);
            }
        });
        txtlamasewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlamasewaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlamasewaKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Jam");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Tambahan");

        cksepatu.setText("Sepatu");
        cksepatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cksepatuActionPerformed(evt);
            }
        });

        ckkostum.setText("Kostum");
        ckkostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckkostumActionPerformed(evt);
            }
        });

        btnhitung.setBackground(new java.awt.Color(153, 0, 51));
        btnhitung.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        btnhitung.setForeground(new java.awt.Color(255, 255, 255));
        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel18.setText("=========Proses Futsalz==========");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnhitung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(ckkostum)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdnindoor)
                                .addGap(18, 18, 18)
                                .addComponent(rdnoutdoor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbjenislap, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtlamasewa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(cksepatu))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdnindoor)
                    .addComponent(rdnoutdoor))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbjenislap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlamasewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cksepatu))
                .addGap(32, 32, 32)
                .addComponent(ckkostum)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhitung)
                    .addComponent(jButton2))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdnindoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnindoorActionPerformed
        if(rdnindoor.isSelected()){
            txttipelapanganvoice.setText("Lapangan Indoor");
        }
        String jenislap = (String) cmbjenislap.getSelectedItem();
        if (rdnindoor.isSelected()) {
            switch(jenislap){
            case "Reguler":
                lblbayar.setText("300000");
            break;
            case "Matras":
                lblbayar.setText("250000");
            break;
            case "Rumput":
                lblbayar.setText("200000");
            break;
            default:
                lblbayar.setText("-");
        }
        } else if(rdnoutdoor.isSelected()){
            switch(jenislap){
            case "Reguler":
                lblbayar.setText("250000");
            break;
            case "Matras":
                lblbayar.setText("200000");
            break;
            case "Rumput":
                lblbayar.setText("150000");
            break;
            default:
                lblbayar.setText("-");
        }
        }
    }//GEN-LAST:event_rdnindoorActionPerformed

    private void txtlamasewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlamasewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlamasewaActionPerformed

    private void txttipelapanganvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipelapanganvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipelapanganvoiceActionPerformed

    private void txtjenislapvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjenislapvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjenislapvoiceActionPerformed

    private void txtlamavoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlamavoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlamavoiceActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        //
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianActionPerformed

    private void rdnoutdoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnoutdoorActionPerformed
        if(rdnoutdoor.isSelected()){
            txttipelapanganvoice.setText("Lapangan Outdoor");
        }
        String jenislap = (String) cmbjenislap.getSelectedItem();
        if (rdnindoor.isSelected()) {
            switch(jenislap){
            case "Reguler":
                lblbayar.setText("300000");
            break;
            case "Matras":
                lblbayar.setText("250000");
            break;
            case "Rumput":
                lblbayar.setText("200000");
            break;
            default:
                lblbayar.setText("-");
        }
        } else if(rdnoutdoor.isSelected()){
            
            switch(jenislap){
            case "Reguler":
                lblbayar.setText("250000");
            break;
            case "Matras":
                lblbayar.setText("200000");
            break;
            case "Rumput":
                lblbayar.setText("150000");
            break;
            default:
                lblbayar.setText("-");
        }
        }
    }//GEN-LAST:event_rdnoutdoorActionPerformed

    private void cmbjenislapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjenislapActionPerformed
        String jenislap = (String) cmbjenislap.getSelectedItem();
        switch(jenislap){
            case "Reguler":
                txtjenislapvoice.setText("Reguler");
            break;
            case "Matras":
                txtjenislapvoice.setText("Matras");
            break;
            case "Rumput":
                txtjenislapvoice.setText("Rumput");
            break;
            default:
            txtjenislapvoice.setText("");
        }
        
        if (rdnindoor.isSelected()) {
            switch(jenislap){
            case "Reguler":
                lblbayar.setText("300000");
            break;
            case "Matras":
                lblbayar.setText("250000");
            break;
            case "Rumput":
                lblbayar.setText("200000");
            break;
            default:
                lblbayar.setText("-");
        }
        } else if(rdnoutdoor.isSelected()){
            switch(jenislap){
            case "Reguler":
                lblbayar.setText("250000");
            break;
            case "Matras":
                lblbayar.setText("200000");
            break;
            case "Rumput":
                lblbayar.setText("150000");
            break;
            default:
                lblbayar.setText("-");
        }
        }
    }//GEN-LAST:event_cmbjenislapActionPerformed

    private void txtlamasewaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlamasewaKeyPressed
//        txtlamavoice.setText(evt);
    }//GEN-LAST:event_txtlamasewaKeyPressed

    private void txtlamasewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlamasewaKeyReleased
        String get = txtlamasewa.getText();
        txtlamavoice.setText(get);
    }//GEN-LAST:event_txtlamasewaKeyReleased

    private void cksepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cksepatuActionPerformed
        if (cksepatu.isSelected()) {
            cksepatuvoice.setSelected(true);
            lblbayarsepatu.setText("50000");
        } else {
            cksepatuvoice.setSelected(false);
            lblbayarsepatu.setText("-");
        }
    }//GEN-LAST:event_cksepatuActionPerformed

    private void ckkostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckkostumActionPerformed
        if (ckkostum.isSelected()) {
            ckkostumvoice.setSelected(true);
            lblbayarkostum.setText("45000");
        } else {
            ckkostumvoice.setSelected(false);
            lblbayarkostum.setText("-");
        }
    }//GEN-LAST:event_ckkostumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void clear(){
        buttonGroup1.clearSelection();
        txttipelapanganvoice.setText("");
        txtjenislapvoice.setText("");
        cmbjenislap.setSelectedIndex(0);
        txtlamasewa.setText("");
        txtlamavoice.setText("");
        cksepatu.setSelected(false);
        cksepatuvoice.setSelected(false);
        ckkostum.setSelected(false);
        ckkostumvoice.setSelected(false);
        txttotal.setText("");
        txtbayar.setText("");
        txtkembalian.setText("");
        lblbayar.setText("-");
        lblbayarkostum.setText("-");
        lblbayarsepatu.setText("-"); 
    }
    
    
    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        try {
        int sepatu = 0,kostum =0,tambahan,lama,lapangan;
        String output;
        lama = Integer.parseInt(txtlamasewa.getText());
        if(cksepatu.isSelected()){
            sepatu = 50000;
        }
        
        if(ckkostum.isSelected()){
            kostum = 45000;
        }
        
        tambahan = (sepatu + kostum) * lama;
        
        lapangan = Integer.parseInt(lblbayar.getText());
        total = (lapangan * lama) + (tambahan *lama);
        output = Integer.toString(total);
        txttotal.setText(output);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Isi Terlebih Dahulu");
        }
    }//GEN-LAST:event_btnhitungActionPerformed

    private void txtbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyTyped
        //
    }//GEN-LAST:event_txtbayarKeyTyped

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        try {
            String output;
            tunai = Integer.parseInt(txtbayar.getText());
          if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                kembalian = tunai - total;
                output = Integer.toString(kembalian);
                if(!"".equals(txttotal.getText())){
                    if(kembalian < 0){
                        txtkembalian.setText("Uang Tidak Cukup"); 
                    } else {
                        txtkembalian.setText(output);                                            
                    }
                } 
                else {
                    JOptionPane.showMessageDialog(this, "Hitung Terlebih Dahulu");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Isi Terlebih Dahulu");
        }
    }//GEN-LAST:event_txtbayarKeyReleased

    private void txtbayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyPressed
        
    }//GEN-LAST:event_txtbayarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(futsal_primavera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(futsal_primavera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(futsal_primavera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(futsal_primavera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new futsal_primavera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckkostum;
    private javax.swing.JCheckBox ckkostumvoice;
    private javax.swing.JCheckBox cksepatu;
    private javax.swing.JCheckBox cksepatuvoice;
    private javax.swing.JComboBox<String> cmbjenislap;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblbayar;
    private javax.swing.JLabel lblbayar1;
    private javax.swing.JLabel lblbayarkostum;
    private javax.swing.JLabel lblbayarkostum1;
    private javax.swing.JLabel lblbayarsepatu;
    private javax.swing.JLabel lblbayarsepatu1;
    private javax.swing.JRadioButton rdnindoor;
    private javax.swing.JRadioButton rdnoutdoor;
    private javax.swing.JLabel test;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtjenislapvoice;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtlamasewa;
    private javax.swing.JTextField txtlamavoice;
    private javax.swing.JTextField txttipelapanganvoice;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
